# Generated by Django 4.1.6 on 2023-03-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['joined'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['joined'], name='employees_e_joined_20987a_idx'),
        ),
    ]
