# Generated by Django 4.1.6 on 2023-02-09 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('closed', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACT', 'Activ'), ('CSD', 'Closed')], default='ACT', max_length=3)),
                ('category', models.CharField(choices=[('TCK', 'Ticket'), ('INC', 'Incident'), ('SRQ', 'Service Request'), ('CHG', 'Change')], default='TCK', max_length=3)),
                ('priority', models.IntegerField(choices=[('1', 'Low'), ('2', 'Middle'), ('3', 'High')], default='1')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_aut', to=settings.AUTH_USER_MODEL)),
                ('respons_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_res', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
