# Generated by Django 4.1.6 on 2023-02-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketportal', '0002_alter_ticket_closed_alter_ticket_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Middle'), (3, 'High')], default=1),
        ),
    ]
