# Generated by Django 4.1.6 on 2023-03-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketportal', '0004_remove_ticket_closed_remove_ticket_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['created']},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created'], name='ticketporta_created_5818fa_idx'),
        ),
    ]
