# Generated by Django 4.1.6 on 2023-03-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketportal', '0008_alter_ticket_respons_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='respons_user',
        ),
    ]
