# Generated by Django 4.1.6 on 2023-05-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketportal', '0024_alter_ticket_options_ticket_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
