# Generated by Django 4.1.6 on 2023-05-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketportal', '0026_alter_ticket_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='closed',
        ),
    ]
