# Generated by Django 4.1.6 on 2023-05-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketportal', '0027_remove_ticket_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
